<?php

namespace Database\Seeders;

use App\Models\Crop;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;

class CropSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        Crop::truncate();
        Schema::enableForeignKeyConstraints();

        foreach ($this->crops() as $crop) {
            Crop::create($crop);
        }
    }

    private function crops(): array
    {
        $ln = fn ($hi, $pa, $ta, $te, $bn, $mr) => ['hindi' => $hi, 'punjabi' => $pa, 'tamil' => $ta, 'telugu' => $te, 'bengali' => $bn, 'marathi' => $mr];
        $img = fn ($name) => 'https://source.unsplash.com/800x600/?' . urlencode($name . ' crop farm india');
        $crop = function ($name, $local, $season, $states, $soils, $temp, $rain, $water, $npk, $yield, $duration, $sow, $harvest, $desc, $precautions) use ($img) {
            return [
                'name' => $name,
                'local_names' => $local,
                'season' => $season,
                'suitable_states' => $states,
                'suitable_soils' => $soils,
                'min_temp' => $temp[0],
                'max_temp' => $temp[1],
                'min_rainfall' => $rain[0],
                'max_rainfall' => $rain[1],
                'water_requirement' => $water,
                'fertilizer_npk' => ['N' => $npk[0], 'P' => $npk[1], 'K' => $npk[2]],
                'organic_fertilizer' => 'Apply 2-4 tonnes FYM or compost per acre with seed treatment using biofertilizer where available.',
                'yield_per_acre' => ['min' => $yield[0], 'max' => $yield[1], 'unit' => $yield[2]],
                'duration_days' => $duration,
                'sowing_months' => $sow,
                'harvest_months' => $harvest,
                'description' => $desc,
                'precautions' => $precautions,
                'image_url' => $img($name),
            ];
        };

        return [
            $crop('Rice/Paddy', $ln('Dhan', 'Dhan', 'Nel', 'Vari', 'Dhan', 'Tandul'), 'kharif', ['West Bengal','Assam','Odisha','Chhattisgarh','Bihar','Uttar Pradesh','Punjab','Haryana','Tamil Nadu','Andhra Pradesh','Telangana','Kerala','Jharkhand','Madhya Pradesh'], ['Clay','Loamy','Clay-Loam','Alluvial'], [22,35], [1000,2000], 'high', [45,24,24], [18,32,'quintal'], 130, ['June','July'], ['October','November'], 'Staple cereal suited to humid kharif conditions and standing water management.', ['Maintain bunds and drainage','Avoid excess nitrogen','Scout for stem borer and blast']),
            $crop('Cotton', $ln('Kapas', 'Kapas', 'Paruthi', 'Patti', 'Kapas', 'Kapus'), 'kharif', ['Gujarat','Maharashtra','Telangana','Andhra Pradesh','Rajasthan','Punjab','Haryana','Madhya Pradesh','Karnataka'], ['Black','Sandy-Loam'], [25,35], [500,1000], 'medium', [60,30,30], [7,14,'quintal kapas'], 170, ['June','July'], ['November','December','January'], 'Deep-rooted fibre crop performing best in black and well-drained sandy loam soils.', ['Use pheromone traps','Avoid waterlogging','Rotate insecticide groups']),
            $crop('Maize/Corn', $ln('Makka', 'Makai', 'Makka Cholam', 'Mokka Jonna', 'Bhutta', 'Maka'), 'kharif', ['Uttar Pradesh','Bihar','Rajasthan','Madhya Pradesh','Karnataka','Andhra Pradesh','Himachal Pradesh','Uttarakhand','Punjab'], ['Loamy','Sandy-Loam','Red','Alluvial'], [21,30], [600,1100], 'medium', [60,30,20], [18,35,'quintal'], 100, ['June','July'], ['September','October'], 'High-yield cereal suitable for diverse Indian kharif belts with good drainage.', ['Control fall armyworm early','Avoid moisture stress at tasseling','Use treated seed']),
            $crop('Soybean', $ln('Soyabean', 'Soyabean', 'Soya', 'Soya Chikkudu', 'Soyabean', 'Soyabean'), 'kharif', ['Madhya Pradesh','Maharashtra','Rajasthan','Karnataka','Telangana','Chhattisgarh'], ['Loamy','Black','Clay'], [20,30], [600,1000], 'medium', [20,40,20], [8,14,'quintal'], 105, ['June','July'], ['September','October'], 'Protein-rich oilseed pulse crop suited to central Indian monsoon regions.', ['Ensure rhizobium seed treatment','Avoid continuous soybean','Keep field weed-free early']),
            $crop('Groundnut', $ln('Moongfali', 'Moongfali', 'Verkadalai', 'Verusenaga', 'Chinabadam', 'Bhuimug'), 'kharif', ['Gujarat','Andhra Pradesh','Tamil Nadu','Rajasthan','Karnataka','Madhya Pradesh','Maharashtra'], ['Sandy','Sandy-Loam','Red'], [25,35], [500,1000], 'medium', [20,40,20], [8,16,'quintal pods'], 115, ['June','July'], ['October','November'], 'Oilseed crop needing loose soil for pegging and pod formation.', ['Apply gypsum at flowering','Avoid heavy clay soil','Dry pods before storage']),
            $crop('Sugarcane', $ln('Ganna', 'Ganna', 'Karumbu', 'Cheruku', 'Akh', 'Oos'), 'kharif', ['Uttar Pradesh','Maharashtra','Karnataka','Tamil Nadu','Andhra Pradesh','Bihar','Gujarat','Haryana','Uttarakhand'], ['Loamy','Clay-Loam','Black','Alluvial'], [20,35], [1200,1500], 'high', [120,60,60], [350,550,'quintal cane'], 360, ['February','March','July'], ['December','January','February'], 'Long-duration cash crop needing fertile soil and assured moisture.', ['Use healthy setts','Manage borers','Trash mulch to conserve moisture']),
            $crop('Bajra/Millet', $ln('Bajra', 'Bajra', 'Kambu', 'Sajja', 'Bajra', 'Bajri'), 'kharif', ['Rajasthan','Maharashtra','Gujarat','Uttar Pradesh','Haryana','Madhya Pradesh','Karnataka'], ['Sandy','Sandy-Loam'], [25,35], [200,600], 'low', [30,15,10], [6,12,'quintal grain'], 85, ['June','July'], ['September','October'], 'Drought-tolerant millet ideal for arid and semi-arid regions.', ['Thin seedlings timely','Avoid excess irrigation','Watch for downy mildew']),
            $crop('Jowar/Sorghum', $ln('Jowar', 'Jowar', 'Cholam', 'Jonna', 'Jowar', 'Jwari'), 'kharif', ['Maharashtra','Karnataka','Madhya Pradesh','Andhra Pradesh','Rajasthan','Tamil Nadu','Gujarat'], ['Loamy','Black','Clay-Loam'], [26,34], [400,1000], 'low', [40,20,20], [8,15,'quintal grain'], 110, ['June','July'], ['October','November'], 'Hardy cereal and fodder crop suited to rainfed Deccan and central zones.', ['Use shoot fly tolerant varieties','Avoid dense sowing','Harvest at physiological maturity']),
            $crop('Tur/Arhar', $ln('Arhar', 'Arhar', 'Thuvarai', 'Kandulu', 'Arhar', 'Tur'), 'kharif', ['Maharashtra','Uttar Pradesh','Madhya Pradesh','Karnataka','Gujarat','Andhra Pradesh','Jharkhand','Bihar'], ['Loamy','Sandy-Loam','Red'], [26,35], [600,1000], 'medium', [20,40,20], [5,10,'quintal grain'], 170, ['June','July'], ['December','January'], 'Deep-rooted pulse crop useful for intercropping and soil fertility.', ['Prevent waterlogging','Monitor pod borer','Use rhizobium culture']),
            $crop('Moong Dal', $ln('Moong', 'Moong', 'Pachai Payaru', 'Pesara', 'Mug', 'Mug'), 'kharif', ['Rajasthan','Uttar Pradesh','Madhya Pradesh','Andhra Pradesh','Maharashtra','Punjab'], ['Sandy-Loam','Loamy'], [28,35], [300,700], 'low', [12,30,10], [3,6,'quintal grain'], 65, ['June','July'], ['August','September'], 'Short-duration pulse crop suitable for kharif and catch-crop windows.', ['Avoid excessive moisture','Harvest pods in pickings','Use yellow mosaic resistant varieties']),
            $crop('Wheat', $ln('Gehu', 'Kanak', 'Godhumai', 'Godhuma', 'Gom', 'Gahu'), 'rabi', ['Punjab','Haryana','Uttar Pradesh','Bihar','Madhya Pradesh','Rajasthan','Gujarat','Uttarakhand','J&K','Himachal Pradesh'], ['Loamy','Clay-Loam','Sandy-Loam','Alluvial'], [10,25], [250,750], 'medium', [60,30,20], [18,28,'quintal grain'], 125, ['November','December'], ['March','April'], 'Major rabi cereal requiring cool growing weather and timely irrigation.', ['Use rust-resistant varieties','Avoid late sowing','Irrigate at crown root initiation']),
            $crop('Mustard/Canola', $ln('Sarson', 'Sarson', 'Kadugu', 'Avalu', 'Sorse', 'Mohari'), 'rabi', ['Rajasthan','Uttar Pradesh','Haryana','Madhya Pradesh','Bihar','West Bengal','Gujarat'], ['Loamy','Sandy-Loam'], [10,25], [250,500], 'low', [40,20,15], [5,9,'quintal seed'], 120, ['October','November'], ['February','March'], 'Oilseed crop suited to cool dry rabi conditions.', ['Control aphids at threshold','Do not over-irrigate','Apply sulfur in deficient soils']),
            $crop('Gram/Chickpea', $ln('Chana', 'Chana', 'Kondakadalai', 'Senagalu', 'Chhola', 'Harbhara'), 'rabi', ['Madhya Pradesh','Rajasthan','Maharashtra','Uttar Pradesh','Andhra Pradesh','Karnataka','Bihar'], ['Loamy','Sandy-Loam','Clay-Loam'], [10,25], [300,700], 'low', [20,40,20], [5,10,'quintal grain'], 115, ['October','November'], ['February','March'], 'Rabi pulse that performs well on conserved soil moisture.', ['Avoid waterlogging','Seed treat for wilt','Use pod borer traps']),
            $crop('Lentil/Masoor', $ln('Masoor', 'Masoor', 'Masoor Paruppu', 'Masura', 'Musur', 'Masur'), 'rabi', ['Uttar Pradesh','Madhya Pradesh','Bihar','West Bengal','Rajasthan'], ['Loamy','Sandy-Loam'], [15,25], [250,500], 'low', [15,35,10], [4,8,'quintal grain'], 110, ['October','November'], ['February','March'], 'Cool-season pulse suitable for eastern and central rabi systems.', ['Avoid acidic unmanaged soils','Use rhizobium treatment','Harvest before pod shattering']),
            $crop('Barley', $ln('Jau', 'Jau', 'Barley', 'Barley', 'Job', 'Satu'), 'rabi', ['Uttar Pradesh','Rajasthan','Punjab','Haryana','Bihar','Himachal Pradesh','J&K'], ['Loamy','Sandy-Loam'], [12,25], [300,600], 'low', [40,20,20], [14,24,'quintal grain'], 120, ['November','December'], ['March','April'], 'Rabi cereal adapted to lower fertility and drier conditions than wheat.', ['Avoid lodging from excess nitrogen','Use clean seed','Control loose smut']),
            $crop('Sunflower', $ln('Surajmukhi', 'Surajmukhi', 'Suryakanthi', 'Poddu Tirugudu', 'Surjomukhi', 'Suryaphul'), 'rabi', ['Karnataka','Andhra Pradesh','Tamil Nadu','Maharashtra','Odisha','Uttar Pradesh','Bihar'], ['Loamy','Sandy-Loam','Black'], [18,35], [600,1000], 'medium', [40,30,20], [5,9,'quintal seed'], 95, ['January','February'], ['April','May'], 'Oilseed crop useful in irrigated rabi and spring rotations.', ['Ensure pollinator activity','Avoid moisture stress at flowering','Control leaf spot']),
            $crop('Potato', $ln('Aloo', 'Aloo', 'Urulai', 'Bangaladumpa', 'Alu', 'Batata'), 'rabi', ['Uttar Pradesh','West Bengal','Bihar','Gujarat','Punjab','Madhya Pradesh','Assam','Himachal Pradesh'], ['Loamy','Sandy-Loam'], [15,25], [400,600], 'medium', [70,50,70], [80,140,'quintal tubers'], 100, ['October','November'], ['January','February'], 'Cool-season vegetable requiring loose fertile soil and regular moisture.', ['Use certified seed tubers','Prevent late blight','Avoid waterlogging']),
            $crop('Onion', $ln('Pyaz', 'Ganda', 'Vengayam', 'Ullipaya', 'Peyaj', 'Kanda'), 'rabi', ['Maharashtra','Karnataka','Madhya Pradesh','Gujarat','Rajasthan','Bihar','Andhra Pradesh'], ['Sandy-Loam','Loamy','Clay-Loam'], [13,25], [350,500], 'medium', [50,30,40], [80,140,'quintal bulbs'], 120, ['October','November'], ['March','April'], 'Bulb crop needing cool vegetative phase and dry maturity.', ['Avoid over-irrigation near harvest','Manage thrips','Cure bulbs after harvest']),
            $crop('Watermelon', $ln('Tarbooz', 'Hadwana', 'Dharpoosani', 'Puchakaya', 'Tormuj', 'Kalingad'), 'zaid', ['Uttar Pradesh','Punjab','Andhra Pradesh','Karnataka','Gujarat','Rajasthan'], ['Sandy','Sandy-Loam'], [24,35], [400,600], 'medium', [40,25,25], [100,180,'quintal fruits'], 90, ['February','March'], ['May','June'], 'Summer cucurbit crop best on riverbeds and sandy loams.', ['Use drip irrigation','Protect from fruit fly','Avoid water stress during fruiting']),
            $crop('Cucumber', $ln('Kheera', 'Kheera', 'Vellarikkai', 'Dosakaya', 'Shosha', 'Kakdi'), 'zaid', ['Uttar Pradesh','Maharashtra','Karnataka','Andhra Pradesh','Tamil Nadu','Gujarat'], ['Sandy-Loam','Loamy'], [22,32], [400,600], 'medium', [35,25,25], [70,120,'quintal fruits'], 60, ['February','March'], ['April','May','June'], 'Short-duration summer vegetable suited to warm irrigated conditions.', ['Use trellis where possible','Control downy mildew','Harvest frequently']),
            $crop('Jute', $ln('Patson', 'Jute', 'Sanal', 'Janumu', 'Pat', 'Ambadi'), 'kharif', ['West Bengal','Assam','Bihar','Odisha','Meghalaya'], ['Loamy','Clay-Loam','Alluvial'], [24,37], [1500,2500], 'high', [40,20,20], [10,18,'quintal fibre'], 130, ['March','April','May'], ['July','August','September'], 'Fibre crop for warm humid eastern and northeastern alluvial belts.', ['Ret properly for fibre quality','Thin dense stands','Maintain weed-free early crop']),
            $crop('Tea', $ln('Chai', 'Chah', 'Thenir', 'Tea', 'Cha', 'Chaha'), 'kharif', ['Assam','West Bengal','Kerala','Tamil Nadu','Himachal Pradesh','Uttarakhand','Tripura'], ['Laterite','Loamy','Well-drained acidic'], [20,30], [1500,3000], 'high', [90,45,90], [600,1200,'kg made tea'], 365, ['April','May','June'], ['Year-round'], 'Perennial plantation crop for humid acidic hill and valley soils.', ['Maintain drainage','Prune on schedule','Manage tea mosquito bug']),
            $crop('Rubber', $ln('Rubber', 'Rubber', 'Rappar', 'Rubber', 'Rubber', 'Rubber'), 'kharif', ['Kerala','Tamil Nadu','Karnataka','Assam','Tripura','Meghalaya'], ['Laterite','Red','Loamy'], [25,35], [2000,4500], 'high', [50,25,50], [600,1000,'kg latex'], 365, ['June','July'], ['Year-round'], 'Perennial latex crop for humid tropical high rainfall regions.', ['Avoid waterlogged planting pits','Use windbreaks','Follow proper tapping panel care']),
            $crop('Coconut', $ln('Nariyal', 'Nariyal', 'Thengai', 'Kobbari', 'Narkel', 'Naral'), 'kharif', ['Kerala','Tamil Nadu','Karnataka','Andhra Pradesh','Goa','West Bengal','Odisha','Assam'], ['Sandy','Sandy-Loam','Laterite'], [27,35], [1500,3000], 'high', [80,40,120], [60,100,'nuts per palm'], 365, ['June','July'], ['Year-round'], 'Coastal and humid-zone perennial palm crop.', ['Mulch basins','Control rhinoceros beetle','Provide irrigation in summer']),
            $crop('Coffee', $ln('Coffee', 'Coffee', 'Kapi', 'Coffee', 'Coffee', 'Coffee'), 'kharif', ['Karnataka','Kerala','Tamil Nadu'], ['Loamy','Laterite','Red'], [15,28], [1500,2500], 'high', [60,40,60], [350,700,'kg clean coffee'], 365, ['June','July'], ['December','January','February'], 'Shade-grown plantation crop for Western Ghats highlands.', ['Maintain shade regulation','Prevent berry borer','Ensure soil conservation']),
            $crop('Cardamom', $ln('Elaichi', 'Elaichi', 'Elakkai', 'Yalakulu', 'Elach', 'Velchi'), 'kharif', ['Kerala','Karnataka','Tamil Nadu','Sikkim','Arunachal Pradesh','Assam','Meghalaya','Mizoram','Nagaland','Tripura'], ['Loamy','Laterite'], [10,35], [1500,4000], 'high', [45,30,60], [150,300,'kg dry capsules'], 365, ['June','July'], ['August','September','October'], 'High-value spice crop for shaded humid hill ecosystems.', ['Maintain shade and mulch','Avoid drought stress','Control capsule rot']),
            $crop('Turmeric', $ln('Haldi', 'Haldi', 'Manjal', 'Pasupu', 'Holud', 'Halad'), 'kharif', ['Andhra Pradesh','Telangana','Odisha','West Bengal','Maharashtra','Tamil Nadu','Kerala','Karnataka'], ['Loamy','Clay-Loam','Black'], [20,30], [1500,2500], 'high', [60,30,60], [80,120,'quintal fresh rhizomes'], 240, ['May','June'], ['January','February'], 'Rhizome spice crop needing warm humid conditions and fertile soil.', ['Use disease-free seed rhizomes','Mulch after planting','Avoid stagnant water']),
            $crop('Ginger', $ln('Adrak', 'Adrak', 'Inji', 'Allam', 'Ada', 'Aale'), 'kharif', ['Kerala','Meghalaya','Assam','Odisha','Andhra Pradesh','West Bengal','Sikkim'], ['Loamy','Sandy-Loam','Laterite'], [20,30], [1500,2500], 'high', [50,30,30], [60,100,'quintal fresh rhizomes'], 230, ['April','May'], ['December','January'], 'Spice crop suited to humid, well-drained soils and partial shade.', ['Treat rhizomes before planting','Mulch heavily','Prevent soft rot']),
            $crop('Chilli', $ln('Mirch', 'Mirch', 'Milagai', 'Mirapa', 'Lonka', 'Mirchi'), 'kharif', ['Andhra Pradesh','Telangana','Maharashtra','Karnataka','West Bengal','Odisha','Rajasthan'], ['Loamy','Sandy-Loam','Black'], [20,30], [600,1200], 'medium', [50,25,25], [15,30,'quintal dry chilli'], 150, ['June','July'], ['November','December','January'], 'Spice and vegetable crop suited to warm conditions and well-drained soils.', ['Control thrips and mites','Avoid waterlogging','Use virus-free seedlings']),
            $crop('Tomato', $ln('Tamatar', 'Tamatar', 'Thakkali', 'Tamata', 'Tomato', 'Tomato'), 'rabi', ['Madhya Pradesh','Karnataka','Andhra Pradesh','Odisha','West Bengal','Bihar','Maharashtra','Gujarat','Himachal Pradesh'], ['Sandy-Loam','Loamy','Red'], [18,27], [600,1200], 'medium', [60,40,40], [100,180,'quintal fruits'], 110, ['October','November'], ['January','February','March'], 'High-value vegetable crop requiring mild temperatures and careful disease management.', ['Stake plants','Prevent wilt and blight','Avoid overhead irrigation']),
        ];
    }
}
