import { useState } from 'react'
import toast from 'react-hot-toast'
import Layout from '../components/layout/Layout'
import Button from '../components/ui/Button'
import FormInput from '../components/ui/FormInput'
import SelectInput from '../components/ui/SelectInput'
import SkeletonCard from '../components/ui/SkeletonCard'
import CropCard from '../components/cards/CropCard'
import { getRecommendation } from '../api/cropApi'
import { fallbackCrops, seasons, soilTypes, states } from '../utils/constants'

export default function CropRecommendationPage() {
  const [form,setForm]=useState({soil_type:'Loamy',state:'Maharashtra',district:'Nashik',season:'Kharif',temperature:29,rainfall:780,water_availability:'Semi-irrigated',budget:'Medium'})
  const [loading,setLoading]=useState(false)
  const [result,setResult]=useState(null)
  const submit=async e=>{e.preventDefault();setLoading(true);try{const data=await getRecommendation({...form,season:form.season.toLowerCase()});setResult(data.result);toast.success('Recommendations ready')}catch{setResult({crops:fallbackCrops,fertilizer_advice:'Use balanced NPK, compost, and micronutrients after soil testing.',ai_guidance:'Fallback guidance generated from local agronomy rules.',calendar:['Land preparation','Seed treatment','Sowing','Irrigation','Fertilizer split','Harvest']});toast.error('Using offline recommendations')}finally{setLoading(false)}}
  return <Layout><div className="grid gap-6 xl:grid-cols-[420px_1fr]"><form onSubmit={submit} className="rounded-2xl bg-white p-6 shadow-sm dark:bg-slate-900"><h1 className="text-2xl font-extrabold">Crop Recommendation</h1><div className="mt-5 space-y-4"><SelectInput label="Soil type" options={soilTypes} value={form.soil_type} onChange={e=>setForm({...form,soil_type:e.target.value})}/><SelectInput label="State" options={states} value={form.state} onChange={e=>setForm({...form,state:e.target.value})}/><FormInput label="District" value={form.district} onChange={e=>setForm({...form,district:e.target.value})}/><SelectInput label="Season" options={seasons} value={form.season} onChange={e=>setForm({...form,season:e.target.value})}/><label className="block text-sm font-semibold">Average temperature: {form.temperature}°C<input className="input-range mt-2 w-full" type="range" min="10" max="45" value={form.temperature} onChange={e=>setForm({...form,temperature:e.target.value})}/></label><label className="block text-sm font-semibold">Average rainfall: {form.rainfall}mm<input className="input-range mt-2 w-full" type="range" min="0" max="3000" value={form.rainfall} onChange={e=>setForm({...form,rainfall:e.target.value})}/></label><SelectInput label="Water availability" options={['Irrigated','Rainfed','Semi-irrigated']} value={form.water_availability} onChange={e=>setForm({...form,water_availability:e.target.value})}/><SelectInput label="Budget" options={['Low','Medium','High']} value={form.budget} onChange={e=>setForm({...form,budget:e.target.value})}/><Button disabled={loading} className="w-full">{loading?'Analyzing...':'Get Recommendations'}</Button></div></form><div>{loading && <div className="grid gap-4 md:grid-cols-3"><SkeletonCard/><SkeletonCard/><SkeletonCard/></div>}{result && <div className="space-y-6"><div className="grid gap-4 md:grid-cols-3">{result.crops.map((c,i)=><CropCard key={c.id||c.name} crop={c} rank={i+1}/>)}</div><div className="rounded-2xl bg-white p-6 shadow-sm dark:bg-slate-900"><h2 className="text-xl font-bold">Fertilizer Recommendations</h2><p className="mt-2">{result.fertilizer_advice}</p><h2 className="mt-6 text-xl font-bold">Farming Calendar</h2><div className="mt-3 flex flex-wrap gap-2">{result.calendar.map(step=><span key={step} className="rounded-full bg-primary-50 px-3 py-1 text-sm font-semibold text-primary-700 dark:bg-primary-900/30 dark:text-primary-200">{step}</span>)}</div><h2 className="mt-6 text-xl font-bold">AI Guidance</h2><p className="mt-2 text-slate-600 dark:text-slate-300">{result.ai_guidance}</p><div className="mt-5 flex gap-2"><Button variant="secondary">Download PDF</Button><Button>Save to History</Button></div></div></div>}</div></div></Layout>
}
