import { useEffect, useState } from 'react'
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { CloudRain, Droplets, Thermometer, Wind } from 'lucide-react'
import Layout from '../components/layout/Layout'
import StatCard from '../components/cards/StatCard'
import ChartCard from '../components/cards/ChartCard'
import CropCard from '../components/cards/CropCard'
import PestCard from '../components/cards/PestCard'
import SchemeCard from '../components/cards/SchemeCard'
import SkeletonCard from '../components/ui/SkeletonCard'
import { getSummary } from '../api/dashboardApi'
import { fallbackAlerts, fallbackCrops, fallbackSchemes } from '../utils/constants'

export default function FarmerDashboard() {
  const [data,setData]=useState(null)
  useEffect(()=>{ getSummary().then(setData).catch(()=>setData({ weather:{temperature:29,humidity:64,wind_speed:12,rainfall:2}, weekly_rainfall:[{day:'Mon',rainfall:2},{day:'Tue',rainfall:8},{day:'Wed',rainfall:4}], temperature_trend:[{day:'Mon',temperature:28},{day:'Tue',temperature:31},{day:'Wed',temperature:29}], yield_prediction:[{month:'Jun',yield:18},{month:'Jul',yield:24},{month:'Aug',yield:32}], alerts:fallbackAlerts, recommended_crops:fallbackCrops, schemes:fallbackSchemes, tips:['Scout fields after rain','Use mulching','Split nitrogen doses'], irrigation:'Avoid irrigation if rainfall exceeds 5 mm today.' })) },[])
  if(!data) return <Layout><div className="grid gap-4 md:grid-cols-3"><SkeletonCard/><SkeletonCard/><SkeletonCard/></div></Layout>
  const w=data.weather
  return <Layout><div className="space-y-6"><h1 className="text-3xl font-extrabold">Farmer Dashboard</h1><div className="grid gap-4 md:grid-cols-4"><StatCard icon={Thermometer} label="Today's Temperature" value={`${w.temperature}°C`}/><StatCard icon={Droplets} label="Humidity" value={`${w.humidity}%`}/><StatCard icon={Wind} label="Wind Speed" value={`${w.wind_speed} km/h`}/><StatCard icon={CloudRain} label="Rainfall" value={`${w.rainfall} mm`}/></div>{data.alerts?.some(a=>a.severity==='critical') && <div className="animate-pulse rounded-2xl bg-red-600 p-4 font-bold text-white">Critical pest alert active in monitored regions. Review emergency actions.</div>}<div className="grid gap-5 xl:grid-cols-3"><ChartCard title="Weekly Rainfall"><ResponsiveContainer><BarChart data={data.weekly_rainfall}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="day"/><YAxis/><Tooltip/><Bar dataKey="rainfall" fill="#16a34a"/></BarChart></ResponsiveContainer></ChartCard><ChartCard title="Temperature Trend"><ResponsiveContainer><LineChart data={data.temperature_trend}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="day"/><YAxis/><Tooltip/><Line dataKey="temperature" stroke="#0284c7" strokeWidth={3}/></LineChart></ResponsiveContainer></ChartCard><ChartCard title="Crop Yield Prediction"><ResponsiveContainer><AreaChart data={data.yield_prediction}><XAxis dataKey="month"/><YAxis/><Tooltip/><Area dataKey="yield" stroke="#ca8a04" fill="#fde68a"/></AreaChart></ResponsiveContainer></ChartCard></div><section><h2 className="mb-4 text-xl font-bold">Active Alerts</h2><div className="grid gap-4 lg:grid-cols-2">{data.alerts.map(a=><PestCard key={a.id} alert={a}/>)}</div></section><section><h2 className="mb-4 text-xl font-bold">Quick Recommendations</h2><div className="grid gap-4 md:grid-cols-3">{data.recommended_crops.map((c,i)=><CropCard key={c.id} crop={c} rank={i+1}/>)}</div></section><div className="grid gap-4 lg:grid-cols-2"><div className="rounded-2xl bg-primary-50 p-5 dark:bg-primary-900/30"><h2 className="font-bold">Irrigation Guidance</h2><p className="mt-2">{data.irrigation}</p><p className="mt-3 text-sm">Use mulching, clean channels, and irrigate in early morning.</p></div><div className="rounded-2xl bg-white p-5 shadow-sm dark:bg-slate-900"><h2 className="font-bold">Daily Farming Tips</h2>{data.tips.map(t=><p key={t} className="mt-2 text-sm">• {t}</p>)}</div></div><section><h2 className="mb-4 text-xl font-bold">Schemes Highlight</h2><div className="grid gap-4 md:grid-cols-2">{data.schemes.map(s=><SchemeCard key={s.id} scheme={s}/>)}</div></section></div></Layout>
}
