import { useState } from 'react'
import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { Search } from 'lucide-react'
import Layout from '../components/layout/Layout'
import Button from '../components/ui/Button'
import FormInput from '../components/ui/FormInput'
import WeatherCard from '../components/cards/WeatherCard'
import WeatherIcon from '../components/ui/WeatherIcon'
import AlertBadge from '../components/ui/AlertBadge'
import { getForecast } from '../api/weatherApi'

export default function WeatherPage() {
  const [city,setCity]=useState('Nashik')
  const [data,setData]=useState(null)
  const search=()=>getForecast({city}).then(setData).catch(()=>setData({current:{city,state:'Maharashtra',temperature:29,humidity:66,wind_speed:12,rainfall:2,condition:'Partly cloudy',feels_like:31,visibility:9,uv_index:7,pressure:1010,sunrise:'05:52',sunset:'18:48',recommendations:['Good day for spraying pesticides after 5 PM','Avoid excess irrigation today']},daily:['Today','Thu','Fri','Sat','Sun','Mon','Tue'].map((d,i)=>({day:d,high:30+i%3,low:22+i%2,rain_chance:20+i*8,condition:i%2?'Rain showers':'Sunny',rainfall:i+1})),hourly:Array.from({length:12},(_,i)=>({time:`${8+i}:00`,temperature:27+i%5,rain_chance:10+i*5})),warnings:[{severity:'medium',message:'Moderate humidity may favor fungal disease.'}]}))
  return <Layout><div className="space-y-6"><h1 className="text-3xl font-extrabold">Weather Intelligence</h1><div className="flex max-w-xl gap-2"><FormInput label="City or district" value={city} onChange={e=>setCity(e.target.value)}/><Button className="mt-6" onClick={search}><Search size={16}/>Search</Button></div>{!data ? <Button onClick={search}>Load Weather</Button> : <><WeatherCard weather={data.current}/><div className="grid gap-4 md:grid-cols-4"><div className="rounded-2xl bg-white p-4 dark:bg-slate-900">Feels like <b>{data.current.feels_like}°C</b></div><div className="rounded-2xl bg-white p-4 dark:bg-slate-900">Visibility <b>{data.current.visibility} km</b></div><div className="rounded-2xl bg-white p-4 dark:bg-slate-900">UV index <b>{data.current.uv_index}</b></div><div className="rounded-2xl bg-white p-4 dark:bg-slate-900">Pressure <b>{data.current.pressure} hPa</b></div></div><div className="grid gap-4 md:grid-cols-7">{data.daily.map(d=><div className="rounded-2xl bg-white p-4 text-center shadow-sm dark:bg-slate-900" key={d.day}><WeatherIcon condition={d.condition}/><b className="block">{d.day}</b><span>{d.high}/{d.low}°</span><p className="text-xs text-sky-600">{d.rain_chance}% rain</p></div>)}</div><div className="overflow-x-auto rounded-2xl bg-white p-4 dark:bg-slate-900"><div className="flex gap-3">{data.hourly.map(h=><div key={h.time} className="min-w-24 rounded-xl bg-slate-50 p-3 text-center dark:bg-slate-800"><b>{h.time}</b><p>{h.temperature}°</p><p className="text-xs">{h.rain_chance}%</p></div>)}</div></div><div className="rounded-2xl bg-white p-5 dark:bg-slate-900"><h2 className="font-bold">Rainfall Probability</h2><div className="h-72"><ResponsiveContainer><AreaChart data={data.daily}><XAxis dataKey="day"/><YAxis/><Tooltip/><Area dataKey="rain_chance" fill="#bfdbfe" stroke="#0284c7"/></AreaChart></ResponsiveContainer></div></div><div className="grid gap-4 md:grid-cols-2"><div className="rounded-2xl bg-primary-50 p-5 dark:bg-primary-900/30"><h2 className="font-bold">Farming Recommendations</h2>{data.current.recommendations.map(r=><p key={r} className="mt-2">• {r}</p>)}</div><div className="rounded-2xl bg-white p-5 dark:bg-slate-900"><h2 className="font-bold">Weather Warnings</h2>{(data.warnings||[]).map(w=><p key={w.message} className="mt-3"><AlertBadge severity={w.severity}/> <span className="ml-2">{w.message}</span></p>)}</div></div></>}</div></Layout>
}
