export const states = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
];
export const soilTypes = ["Clay", "Sandy", "Loamy", "Black", "Red", "Laterite"];
export const seasons = ["Kharif", "Rabi", "Zaid"];
export const severityScore = { low: 25, medium: 55, high: 76, critical: 92 };
export const fallbackCrops = [
  {
    id: 1,
    name: "Rice",
    season: "kharif",
    yield_per_acre: "20-30 quintals",
    image_url: "https://source.unsplash.com/featured/?rice",
    suitability_score: 94,
    water_needs: "High",
    fertilizer_recommendation: "Balanced NPK with zinc where deficient.",
  },
  {
    id: 2,
    name: "Wheat",
    season: "rabi",
    yield_per_acre: "18-24 quintals",
    image_url: "https://source.unsplash.com/featured/?wheat",
    suitability_score: 90,
    water_needs: "Medium",
    fertilizer_recommendation: "Split nitrogen with basal phosphorus.",
  },
  {
    id: 3,
    name: "Cotton",
    season: "kharif",
    yield_per_acre: "8-12 quintals",
    image_url: "https://source.unsplash.com/featured/?cotton",
    suitability_score: 86,
    water_needs: "Medium",
    fertilizer_recommendation: "NPK plus micronutrients in black soil.",
  },
];
export const fallbackSchemes = [
  {
    id: 1,
    name: "PM-KISAN",
    ministry: "Ministry of Agriculture",
    benefits: ["Rs. 6,000 per year", "Direct bank transfer", "eKYC enabled"],
    eligibility: "Eligible landholding farmer families.",
    description: "Direct income support for farmers.",
    apply_url: "https://pmkisan.gov.in",
  },
  {
    id: 2,
    name: "Fasal Bima Yojana",
    ministry: "Ministry of Agriculture",
    benefits: ["Crop insurance", "Low premium", "Weather loss cover"],
    eligibility: "Farmers growing notified crops.",
    description: "Insurance protection for crop loss.",
    apply_url: "https://pmfby.gov.in",
  },
];
export const fallbackAlerts = [
  {
    id: 1,
    pest_name: "Brown Plant Hopper",
    severity: "critical",
    affected_states: ["West Bengal", "Odisha"],
    symptoms: "Hopper burn patches and yellowing.",
    prevention: "Avoid excess nitrogen and inspect field base.",
    emergency_action: "Use recommended control after ETL.",
    crop: { name: "Rice" },
  },
  {
    id: 2,
    pest_name: "White Fly",
    severity: "high",
    affected_states: ["Punjab", "Gujarat"],
    symptoms: "Leaf curling and sticky honeydew.",
    prevention: "Yellow sticky traps and weed host removal.",
    emergency_action: "Rotate recommended insecticides.",
    crop: { name: "Cotton" },
  },
];
