import { useEffect, useState } from 'react'
import toast from 'react-hot-toast'
import Layout from '../../components/layout/Layout'
import DataTable from '../../components/ui/DataTable'
import Button from '../../components/ui/Button'
import Modal from '../../components/ui/Modal'
import FormInput from '../../components/ui/FormInput'
import SelectInput from '../../components/ui/SelectInput'
import AlertBadge from '../../components/ui/AlertBadge'
import { createAlert, updateAlert } from '../../api/adminApi'
import { getAlerts } from '../../api/pestApi'
import { toArray } from '../../utils/helpers'

const blank={crop_id:1,pest_name:'',severity:'medium',affected_states:'Maharashtra',symptoms:'',prevention:'',emergency_action:'',is_active:true}
export default function AdminAlerts(){const[alerts,setAlerts]=useState([]),[edit,setEdit]=useState(null);useEffect(()=>{getAlerts().then(setAlerts).catch(()=>setAlerts([]))},[]);const save=async()=>{const payload={...edit,affected_states:toArray(edit.affected_states),crop_id:Number(edit.crop_id),is_active:Boolean(edit.is_active)};const res=edit.id?await updateAlert(edit.id,payload):await createAlert(payload);setAlerts(edit.id?alerts.map(a=>a.id===res.id?res:a):[res,...alerts]);setEdit(null);toast.success('Alert saved')};return <Layout><div className="space-y-4"><div className="flex justify-between"><h1 className="text-3xl font-extrabold">Pest Alerts Management</h1><Button onClick={()=>setEdit(blank)}>Add Alert</Button></div><DataTable columns={[{key:'pest_name',label:'Pest'},{key:'severity',label:'Severity',render:r=><AlertBadge severity={r.severity}/>},{key:'is_active',label:'Active',render:r=>r.is_active?'Yes':'No'}]} data={alerts} actions={a=><Button variant="secondary" onClick={()=>setEdit({...a,affected_states:(a.affected_states||[]).join(', ')})}>Edit</Button>}/><Button variant="secondary">Send Notification to Farmers</Button><Modal open={!!edit} title="Alert Form" onClose={()=>setEdit(null)} footer={<Button onClick={save}>Save</Button>}>{edit&&<div className="grid gap-3 md:grid-cols-2"><FormInput label="Crop ID" type="number" value={edit.crop_id} onChange={e=>setEdit({...edit,crop_id:e.target.value})}/><FormInput label="Pest name" value={edit.pest_name} onChange={e=>setEdit({...edit,pest_name:e.target.value})}/><SelectInput label="Severity" options={['low','medium','high','critical']} value={edit.severity} onChange={e=>setEdit({...edit,severity:e.target.value})}/><FormInput label="Affected states" value={edit.affected_states} onChange={e=>setEdit({...edit,affected_states:e.target.value})}/><textarea className="rounded-lg border p-3 dark:border-slate-700 dark:bg-slate-900" placeholder="Symptoms" value={edit.symptoms} onChange={e=>setEdit({...edit,symptoms:e.target.value})}/><textarea className="rounded-lg border p-3 dark:border-slate-700 dark:bg-slate-900" placeholder="Prevention" value={edit.prevention} onChange={e=>setEdit({...edit,prevention:e.target.value})}/><textarea className="md:col-span-2 rounded-lg border p-3 dark:border-slate-700 dark:bg-slate-900" placeholder="Emergency action" value={edit.emergency_action} onChange={e=>setEdit({...edit,emergency_action:e.target.value})}/><label className="flex gap-2"><input type="checkbox" checked={edit.is_active} onChange={e=>setEdit({...edit,is_active:e.target.checked})}/>Active</label></div>}</Modal></div></Layout>}
