import { useEffect, useState } from 'react'
import toast from 'react-hot-toast'
import Layout from '../../components/layout/Layout'
import DataTable from '../../components/ui/DataTable'
import Modal from '../../components/ui/Modal'
import Button from '../../components/ui/Button'
import FormInput from '../../components/ui/FormInput'
import { createScheme } from '../../api/adminApi'
import { getSchemes } from '../../api/schemeApi'
import { toArray } from '../../utils/helpers'

const blank={name:'',ministry:'',description:'',benefits:'Direct benefit, Advisory support, Farmer service',eligibility:'Eligible farmers as per official scheme rules.',apply_url:'https://pmkisan.gov.in',deadline:'',is_active:true,image_url:'https://images.unsplash.com/photo-1500382017468-9049fed747ef'}
export default function AdminSchemes(){const[schemes,setSchemes]=useState([]),[edit,setEdit]=useState(null);useEffect(()=>{getSchemes().then(setSchemes).catch(()=>setSchemes([]))},[]);const save=async()=>{const payload={...edit,benefits:toArray(edit.benefits),deadline:edit.deadline||null};const res=await createScheme(payload);setSchemes([res,...schemes]);setEdit(null);toast.success('Scheme saved')};return <Layout><div className="space-y-4"><div className="flex justify-between"><h1 className="text-3xl font-extrabold">Schemes Management</h1><Button onClick={()=>setEdit(blank)}>Add Scheme</Button></div><DataTable columns={[{key:'name',label:'Name'},{key:'ministry',label:'Ministry'},{key:'is_active',label:'Active',render:r=>r.is_active?'Yes':'No'}]} data={schemes} actions={s=><Button variant="secondary" onClick={()=>setEdit({...s,benefits:(s.benefits||[]).join(', ')})}>Edit</Button>}/><Modal open={!!edit} title="Scheme Form" onClose={()=>setEdit(null)} footer={<Button onClick={save}>Save</Button>}>{edit&&<div className="grid gap-3 md:grid-cols-2"><FormInput label="Name" value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/><FormInput label="Ministry" value={edit.ministry} onChange={e=>setEdit({...edit,ministry:e.target.value})}/><FormInput label="Benefits" value={edit.benefits} onChange={e=>setEdit({...edit,benefits:e.target.value})}/><FormInput label="Apply URL" value={edit.apply_url} onChange={e=>setEdit({...edit,apply_url:e.target.value})}/><FormInput label="Deadline" type="date" value={edit.deadline||''} onChange={e=>setEdit({...edit,deadline:e.target.value})}/><FormInput label="Image URL" value={edit.image_url} onChange={e=>setEdit({...edit,image_url:e.target.value})}/><textarea className="rounded-lg border p-3 dark:border-slate-700 dark:bg-slate-900" placeholder="Description" value={edit.description} onChange={e=>setEdit({...edit,description:e.target.value})}/><textarea className="rounded-lg border p-3 dark:border-slate-700 dark:bg-slate-900" placeholder="Eligibility" value={edit.eligibility} onChange={e=>setEdit({...edit,eligibility:e.target.value})}/><label className="flex gap-2"><input type="checkbox" checked={edit.is_active} onChange={e=>setEdit({...edit,is_active:e.target.checked})}/>Active</label></div>}</Modal></div></Layout>}
